apiVersion: kibana.k8s.elastic.co/v1alpha1
kind: Kibana
metadata:
  # From this issue: https://github.com/elastic/cloud-on-k8s/issues/942
  name: textsearch-kibana
  namespace: textsearch
spec:
  version: 7.2.0
  nodeCount: 1
  podTemplate:
    spec:
      containers:
      - name: kibana
        env:
        - name: SERVER_BASEPATH
          value: "/kibana"
  elasticsearchRef:
    name: textsearch-es